databases:
  -name: prod_saas_db
  databaseName: prod_saas_db
  user: kaiser

services:
  -type: web
  name: saas_app
  env: ruby
  buildCommand: "./bin/render-build.sh"
  #  startCommand: "bundle exec puma -C config/puma.rb"
  startCommand: bundle exec rails server
  envVars:
    - key: RAILS_MASTER_KEY
      sync: false
    - key: DATABASE_URL
      fromDatabase:
        name: postgres
        property: connectionString
